### PR TITLE
Enable switching between multiple root source files

### PR DESCRIPTION
**Pull request by aumayr**
ref #213 

- `beancount-fava` now accepts multiple filenames
- The title (top left) is now a dropdown where one of the specified
  files can be selected
- The URL for all views is prefixed by a slug generated from the
  filename
- Also update the `test_scrape` function

TODO:

- [ ] Add documentation for this feature, maybe with a screenshot

### CODE REVIEW

**Comment by aumayr** [comment]
@yagebu Please feel free to optimize the code when you see something odd.

**Comment by yagebu** [comment]
Cool, will have a look later today or tomorrow.

> The URL for all views is prefixed by a slug generated from the filename

I suggest using the title (as per beancount option) instead to generate the slug.

**Comment by aumayr** [comment]
Thanks! 

Problem with the title is that you would have to parse all the files for extracting this...

**Comment by yagebu** [comment]
> Problem with the title is that you would have to parse all the files for extracting this...

But that's something we do at startup anyway, right?

**Comment by aumayr** [comment]
But only the currently active file. With this we would have to load all files.

**Comment by yagebu** [comment]
> But only the currently active file. With this we would have to load all files.

I think we should load all files right at startup.
More files -> slower startup = expected
More files -> slow page-load when switching = annoying

The application should maintain a dict of APIs, one for each opened file.

**Comment by aumayr** [comment]
This works really well for me. I think we can merge this. 

What do you think, @yagebu ?

**Pull request merged**
