### PR TITLE
Simple website / docs

### PR DESCRIPTION
**Pull request by yagebu**
Basic website generated by sphinx using the alabaster theme.
Ref #150
https://yagebu.github.io/fava/index.html for a preview.

Todo:
- [x] Add Makefile target (maybe in future: setup travis to automatically push to gh-pages).
- [x] cleanup changelog some more.
- [x] Shorten README to include more the development-related information.
- [x] add longer "Getting Started" guide with reference to included help pages.
- [x] Link to LICENSE

Later:
- [ ] add logo to the top left corner (@aumayr: this seems like something up your ballpark). Another option would be to include a big banner in the content column.

I don't think it makes sense to include the help pages in the website currently. They're available locally anyway and not in best shape at the moment IMHO. Would also add another point where things could get out of sync. Best to start small and concise with the website.

Is the github account @fava controlled by you, @aumayr? The we could use `fava.github.io` to host the webpage, which would be a good URL to start with.

### CODE REVIEW

**Comment by aumayr** [comment]
@yagebu Thank you so much for this - it looks awesome and is exactly what I envisioned!

> I don't think it makes sense to include the help pages in the website currently. They're available locally anyway and not in best shape at the moment IMHO. Would also add another point where things could get out of sync. Best to start small and concise with the website.

Totally agreed. I innocently thought that there might be PRs for the help pages from other people, but looks like I have to become a writer after all :-)

> add logo to the top left corner (@aumayr: this seems like something up your ballpark). Another option would be to include a big banner in the content column.

No problem, will do. 

>  cleanup changelog some more

I saw that you have changed the wording/formulation. I really do not mind that and find that your version reads much nicer. In fact, this is my first OSS project, and so were these the first ones ever for me to write. Do you have some "guidelines", "best practices" or other pointers to resources to use when formulating Release notes/Changelogs? Or did you do this just "out of your head"?

> Any other page that we desperately need?

I think the license and pointers to the Beancount documentation (under the "Development" page) would be good to have. Other than that this should be good for the first go. 

> Is the github account @fava controlled by you, @aumayr? The we could use `fava.github.io` to host the webpage, which would be a good URL to start with.

Nope, I was too slow/stupid to register for that, and I don't know to whom it belongs to. But I would be willing to invest in a nice domain. Now that there are thousands of TLDs to choose from there should be a "fava.[some-new-tld]"-one available at little cost. Any suggestions from the list at https://www.hover.com/domains/results?q=fava (should be under 40-50$ if I carry it alone. But we also could add a donate-button, maybe we can gather the money for the domain.)?

**Comment by yagebu** [comment]
> Totally agreed. I innocently thought that there might be PRs for the help pages from other people, but looks like I have to become a writer after all :-)

I will also write some help pages at some point ;)

> I saw that you have changed the wording/formulation. I really do not mind that and find that your version reads much nicer. In fact, this is my first OSS project, and so were these the first ones ever for me to write. Do you have some "guidelines", "best practices" or other pointers to resources to use when formulating Release notes/Changelogs? Or did you do this just "out of your head"?

I usually just have a look at what other Python projects with good documentation do. Some pointers: [beets](https://beets.readthedocs.org/en) and any [pocoo](http://www.pocoo.org/) project. And in this case also some of the projects given as examples on the page of the [alabaster](https://github.com/bitprophet/alabaster) sphinx theme.

> I think the license and pointers to the Beancount documentation (under the "Development" page) would be good to have. Other than that this should be good for the first go.

:+1: 

> Any suggestions from the list at https://www.hover.com/domains/results?q=fava (should be under 40-50$ if I carry it alone.

Oh wow there's a lot to choose from. I had a quick look and nothing really caught my eye. Maybe we can again find something nicely related to beans etc.. I would also be willing to contribute some money to it.

**Comment by aumayr** [comment]
👍

@yagebu Is there a way I can reach you via email/IM? (personal matter)

**Comment by yagebu** [comment]
> Is there a way I can reach you via email/IM? (fava-related, but personal matter)

You can use the email address I use for commits (`git log` should show it ;) )

**Comment by yagebu** [comment]
I've merged the changes and pushed it to 'gh-pages' (https://aumayr.github.io/fava/). This won't update automatically but `make gh-pages` automates it (careful to only use it when there are no unstaged changes).

**Comment by aumayr** [comment]
> Oh wow there's a lot to choose from. I had a quick look and nothing really caught my eye. Maybe we can again find something nicely related to beans etc...

There are too many, that's the problem ;-) `fava.tool` sounds nice and is short, but I think it generally does not matter too much, because people will find fava via a search engine anyway, and not enter the URL manually.

**Pull request closed without merging**
