### PR TITLE
Beancount code-completer

### PR DESCRIPTION
**Pull request by corani**
- Add syntax highlighting for `custom` and `include` directives
- Initial work on a more functional code-completer for beancount

### CODE REVIEW

**Comment by aumayr** [comment]
@corani This looks awesome! 

Please let me know when I should test it and when it is ready to merge.

**Comment by yagebu** [comment]
I've added linting for all Javascript. I've also consistently indented all of it using 2 spaces, so this needs to be rebased.

Could you also try to fix all linting errors for new code you added? If you've got questions about any of the linting rules, feel free to ask.

**Comment by yagebu** [comment]
Sorry @corani for making this obsolete with #331...

I've implemented most of the auto-completion you've implemented here (but for custom directives and options). Additionally I've added completion for postings.

A PR with more completions would be very welcome of course!

**Comment by corani** [comment]
No problem. I'll have a look at it when I'm back from traveling.

On Thu, Jun 23, 2016, 17:03 Jakob Schnitzer <notifications@github.com>
wrote:

> Closed #327 <https://github.com/aumayr/fava/pull/327>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aumayr/fava/pull/327#event-701598326>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAdWB3834kR71S3E9SeFX8i0WWrV5QWaks5qOkvqgaJpZM4IwzGg>
> .
>
-- 

Best regards,
Daniël Bos

Your government is reading your email. Slow them down with encryption.

My public key: http://goo.gl/gms497 (4096 bit RSA, id EF2D5D91)
Fingerprint  : D8D0 9FBE F075 F709 7B52  2F73 326C 2123 EF2D 5D91

**Pull request closed without merging**
