### PR TITLE
journal: fix balance

### PR DESCRIPTION
**Pull request by yagebu**
ref #147

### CODE REVIEW

**Comment by yagebu** [comment]
Maybe make a release after this one?

**Comment by aumayr** [comment]
@yagebu Thanks for the fix! I will wait for your "go" and then make a new release.

**Comment by aumayr** [comment]
@yagebu Is there something still open here? (Also regarding #143 and obeying filters?)

**Comment by yagebu** [comment]
Only got around to dealing with the filters now: #170; now we're all good as far as I can see.

**Comment by aumayr** [comment]
Perfect, thanks! I'm waiting for others to test the Document upload (drag'n'drop)-feature, and will release a new version tomorrow.

**Pull request merged**
